language: python
python:
  - "3.5"
install:
  - pip3 install pytest==3.0.2 flake8==3.0.4 coveralls==1.1
before_script:
  - flake8 ubuntudesign/documentation_builder
script:
  - ./setup.py test
after_success:
  - coveralls

