name: documentation-builder
version: '0.5.0'
summary: Build HTML documentation from markdown
description: |
  A tool to build repositories of markdown files of documentation into HTML pages

grade: stable
confinement: strict

parts:
  repo:
    plugin: python
    source: https://github.com/CanonicalLtd/documentation-builder.git
  copy:
    plugin: dump
    source: bin

apps:
  documentation-builder:
    plugs:
        - home
    command: wrapper.sh
